---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cypress-test-sa
  namespace: default
  labels:
    name: cypress-test-sa
    app.kubernetes.io/part-of: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cypress-test-sa
  namespace: default
  labels:
    name: cypress-test-sa
    app.kubernetes.io/part-of: litmus
rules:
- apiGroups: [""]
  resources: ["pods","events"]
  verbs: ["create","list","get","patch","update","delete","deletecollection"]
- apiGroups: [""]
  resources: ["pods/exec","pods/log","replicationcontrollers"]
  verbs: ["create","list","get"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","list","get","delete","deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cypress-test-sa
  namespace: default
  labels:
    name: cypress-test-sa
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cypress-test-sa
subjects:
- kind: ServiceAccount
  name: cypress-test-sa
  namespace: default
